export enum TypographyVariant {
  MESSAGE_CONTENT = "MESSAGE_CONTENT",
  CHAT_TITLE = "CHAT_TITLE",
  REGULAR = "REGULAR",
  CONVERSATION_PREVIEW_AUTHOR = "CONVERSATION_PREVIEW_AUTHOR",
  SECTION_TITLE = "SECTION_TITLE",
}
